/**
 * Supabase client configuration
 * Creates and configures the Supabase client for database and authentication operations
 * 
 * This file is automatically generated. Do not edit it directly.
 */

import { createClient } from '@supabase/supabase-js'; // supabase client library
import type { Database } from './types'; // TypeScript database schema types

// Supabase project configuration (public, safe to expose in frontend)
const SUPABASE_URL = "https://hrdncodauqhesawvlbnf.supabase.co"; // project URL
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZG5jb2RhdXFoZXNhd3ZsYm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODkyNTgsImV4cCI6MjA2NzQ2NTI1OH0.B6VFdsDO6miU21W3PBhxkWRDEQQU9GKYPDgESUEPk7M"; // public anon key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// create configured Supabase client with TypeScript support
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // persist auth session in browser storage
    persistSession: true, // keep user logged in across browser sessions
    autoRefreshToken: true, // automatically refresh expired tokens
  }
});